-- Create the Snowflake warehouse
CREATE WAREHOUSE IF NOT EXISTS S8149950_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE S8149950_WH;

-- Create the project database
CREATE DATABASE IF NOT EXISTS S8149950_PEDESTRIAN_DB;

USE DATABASE S8149950_PEDESTRIAN_DB;

-- Create the raw-data schema
CREATE SCHEMA IF NOT EXISTS RAW;

USE SCHEMA RAW;

-- Define the CSV structure
CREATE OR REPLACE FILE FORMAT PEDESTRIAN_CSV_FORMAT
    TYPE = 'CSV'
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- Connect Snowflake to the S3 folder
CREATE OR REPLACE STAGE PEDESTRIAN_S3_STAGE
    URL = 's3://nit2202-s8149950-pedestrian-data/raw-data/'
    FILE_FORMAT = (
        FORMAT_NAME =
        'S8149950_PEDESTRIAN_DB.RAW.PEDESTRIAN_CSV_FORMAT'
    );

-- Confirm that Snowflake can see the CSV
LIST @PEDESTRIAN_S3_STAGE;


-- Inspect the CSV header and suggested data types
USE WAREHOUSE S8149950_WH;
USE DATABASE S8149950_PEDESTRIAN_DB;
USE SCHEMA RAW;

SELECT
    COLUMN_NAME,
    TYPE,
    NULLABLE,
    ORDER_ID
FROM TABLE(
    INFER_SCHEMA(
        LOCATION =>
            '@PEDESTRIAN_S3_STAGE/pedestrian-counting-system-monthly-counts-per-hour.csv',
        FILE_FORMAT => 'PEDESTRIAN_CSV_FORMAT',
        MAX_FILE_COUNT => 1,
        MAX_RECORDS_PER_FILE => 10000
    )
)
ORDER BY ORDER_ID;

-- Create the raw pedestrian-count table
USE WAREHOUSE S8149950_WH;
USE DATABASE S8149950_PEDESTRIAN_DB;
USE SCHEMA RAW; 

CREATE OR REPLACE TABLE PEDESTRIAN_COUNTS_RAW (
    ID                  NUMBER(38, 0),
    LOCATION_ID         NUMBER(10, 0),
    SENSING_DATE        DATE,
    HOURDAY             NUMBER(2, 0),
    DIRECTION_1         NUMBER(10, 0),
    DIRECTION_2         NUMBER(10, 0),
    TOTAL_OF_DIRECTIONS NUMBER(10, 0),
    SENSOR_NAME         VARCHAR(200),
    LOCATION            VARCHAR(200)
);

-- Load the CSV from S3 into the Snowflake table
COPY INTO PEDESTRIAN_COUNTS_RAW
FROM
    @PEDESTRIAN_S3_STAGE/pedestrian-counting-system-monthly-counts-per-hour.csv
FILE_FORMAT = (
    FORMAT_NAME = 'PEDESTRIAN_CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

-- Confirm the number of loaded records
SELECT COUNT(*) AS TOTAL_ROWS
FROM PEDESTRIAN_COUNTS_RAW;

-- Preview the imported data
SELECT *
FROM PEDESTRIAN_COUNTS_RAW
LIMIT 10;

-- Data-quality assessment
WITH DUPLICATE_GROUPS AS (
    SELECT
        LOCATION_ID,
        SENSING_DATE,
        HOURDAY,
        COUNT(*) AS RECORD_COUNT
    FROM PEDESTRIAN_COUNTS_RAW
    GROUP BY
        LOCATION_ID,
        SENSING_DATE,
        HOURDAY
    HAVING COUNT(*) > 1
),
DUPLICATE_SUMMARY AS (
    SELECT
        COUNT(*) AS DUPLICATE_KEY_GROUPS,
        COALESCE(SUM(RECORD_COUNT - 1), 0)
            AS EXTRA_DUPLICATE_ROWS
    FROM DUPLICATE_GROUPS
)
SELECT
    COUNT(*) AS TOTAL_ROWS,
    MIN(SENSING_DATE) AS START_DATE,
    MAX(SENSING_DATE) AS END_DATE,
    COUNT(DISTINCT LOCATION_ID) AS SENSOR_COUNT,

    COUNT_IF(LOCATION_ID IS NULL)
        AS MISSING_LOCATION_ID,

    COUNT_IF(SENSING_DATE IS NULL)
        AS MISSING_DATE,

    COUNT_IF(HOURDAY IS NULL OR HOURDAY NOT BETWEEN 0 AND 23)
        AS INVALID_HOUR,

    COUNT_IF(TOTAL_OF_DIRECTIONS IS NULL)
        AS MISSING_TOTAL_COUNT,

    COUNT_IF(
        TOTAL_OF_DIRECTIONS < 0
        OR DIRECTION_1 < 0
        OR DIRECTION_2 < 0
    ) AS NEGATIVE_COUNTS,

    COUNT_IF(
        DIRECTION_1 IS NOT NULL
        AND DIRECTION_2 IS NOT NULL
        AND TOTAL_OF_DIRECTIONS IS NOT NULL
        AND DIRECTION_1 + DIRECTION_2
            <> TOTAL_OF_DIRECTIONS
    ) AS DIRECTION_TOTAL_MISMATCHES,

    COUNT_IF(
        SENSOR_NAME IS NULL
        OR TRIM(SENSOR_NAME) = ''
    ) AS MISSING_SENSOR_NAME,

    COUNT_IF(
        LOCATION IS NULL
        OR TRIM(LOCATION) = ''
    ) AS MISSING_COORDINATES,

    D.DUPLICATE_KEY_GROUPS,
    D.EXTRA_DUPLICATE_ROWS

FROM PEDESTRIAN_COUNTS_RAW
CROSS JOIN DUPLICATE_SUMMARY D
GROUP BY
    D.DUPLICATE_KEY_GROUPS,
    D.EXTRA_DUPLICATE_ROWS;

-- Create the analytics schema
CREATE SCHEMA IF NOT EXISTS
    S8149950_PEDESTRIAN_DB.ANALYTICS;

-- Create the cleaned Tableau-ready view
CREATE OR REPLACE VIEW
    S8149950_PEDESTRIAN_DB.ANALYTICS.PEDESTRIAN_COUNTS_CLEAN
AS

WITH BASE AS (
    SELECT
        ID,
        LOCATION_ID,
        SENSING_DATE,
        HOURDAY,
        DIRECTION_1,
        DIRECTION_2,
        TOTAL_OF_DIRECTIONS,
        SENSOR_NAME,
        LOCATION,

        TRY_TO_DOUBLE(
            TRIM(SPLIT_PART(LOCATION, ',', 1))
        ) AS LATITUDE,

        TRY_TO_DOUBLE(
            TRIM(SPLIT_PART(LOCATION, ',', 2))
        ) AS LONGITUDE

    FROM S8149950_PEDESTRIAN_DB.RAW.PEDESTRIAN_COUNTS_RAW

    WHERE LOCATION_ID IS NOT NULL
      AND SENSING_DATE IS NOT NULL
      AND HOURDAY BETWEEN 0 AND 23
      AND TOTAL_OF_DIRECTIONS >= 0
)

SELECT
    ID,

    CONCAT(
        LOCATION_ID,
        '-',
        TO_CHAR(SENSING_DATE, 'YYYYMMDD'),
        '-',
        LPAD(HOURDAY::VARCHAR, 2, '0')
    ) AS RECORD_KEY,

    LOCATION_ID,

    COALESCE(
        NULLIF(TRIM(SENSOR_NAME), ''),
        'Sensor ' || LOCATION_ID
    ) AS SENSOR_DISPLAY_NAME,

    SENSING_DATE,

    DATEADD(
        HOUR,
        HOURDAY,
        SENSING_DATE::TIMESTAMP_NTZ
    ) AS SENSING_TIMESTAMP,

    YEAR(SENSING_DATE) AS SENSING_YEAR,
    QUARTER(SENSING_DATE) AS SENSING_QUARTER,
    MONTH(SENSING_DATE) AS MONTH_NUMBER,
    TO_CHAR(SENSING_DATE, 'MMMM') AS MONTH_NAME,
    DATE_TRUNC('MONTH', SENSING_DATE) AS MONTH_START,

    DAYOFWEEKISO(SENSING_DATE) AS DAY_OF_WEEK_NUMBER,
    DAYNAME(SENSING_DATE) AS DAY_OF_WEEK,

    IFF(
        DAYOFWEEKISO(SENSING_DATE) IN (6, 7),
        TRUE,
        FALSE
    ) AS IS_WEEKEND,

    HOURDAY AS HOUR_OF_DAY,

    LPAD(HOURDAY::VARCHAR, 2, '0') || ':00'
        AS HOUR_LABEL,

    CASE
        WHEN HOURDAY BETWEEN 0 AND 5
            THEN 'Early Morning'
        WHEN HOURDAY BETWEEN 6 AND 11
            THEN 'Morning'
        WHEN HOURDAY BETWEEN 12 AND 17
            THEN 'Afternoon'
        ELSE 'Evening'
    END AS TIME_PERIOD,

    CASE
        WHEN HOURDAY BETWEEN 0 AND 5 THEN 1
        WHEN HOURDAY BETWEEN 6 AND 11 THEN 2
        WHEN HOURDAY BETWEEN 12 AND 17 THEN 3
        ELSE 4
    END AS TIME_PERIOD_ORDER,

    DIRECTION_1,
    DIRECTION_2,
    TOTAL_OF_DIRECTIONS AS PEDESTRIAN_COUNT,

    LATITUDE,
    LONGITUDE,

    IFF(
        LATITUDE IS NOT NULL
        AND LONGITUDE IS NOT NULL,
        TRUE,
        FALSE
    ) AS IS_MAPPABLE,

    IFF(
        SENSOR_NAME IS NULL
        OR TRIM(SENSOR_NAME) = ''
        OR LATITUDE IS NULL
        OR LONGITUDE IS NULL,
        'Missing sensor metadata',
        'Complete'
    ) AS DATA_QUALITY_STATUS

FROM BASE;

SELECT
    COUNT(*) AS CLEAN_ROWS,
    COUNT_IF(DATA_QUALITY_STATUS = 'Complete')
        AS COMPLETE_ROWS,
    COUNT_IF(DATA_QUALITY_STATUS = 'Missing sensor metadata')
        AS METADATA_MISSING_ROWS,
    COUNT_IF(IS_MAPPABLE) AS MAPPABLE_ROWS
FROM S8149950_PEDESTRIAN_DB.ANALYTICS.PEDESTRIAN_COUNTS_CLEAN;

SELECT *
FROM S8149950_PEDESTRIAN_DB.ANALYTICS.PEDESTRIAN_COUNTS_CLEAN
LIMIT 10;

-- Point 10: Simple query
-- Top 10 busiest sensors in the complete 2025 calendar year

SELECT
    LOCATION_ID,
    SENSOR_DISPLAY_NAME,
    COUNT(DISTINCT SENSING_DATE) AS ACTIVE_DAYS,
    COUNT(*) AS OBSERVED_HOURS,
    SUM(PEDESTRIAN_COUNT) AS TOTAL_PEDESTRIANS,
    ROUND(AVG(PEDESTRIAN_COUNT), 2)
        AS AVG_PEDESTRIANS_PER_HOUR
FROM S8149950_PEDESTRIAN_DB.ANALYTICS.PEDESTRIAN_COUNTS_CLEAN
WHERE SENSING_YEAR = 2025
  AND DATA_QUALITY_STATUS = 'Complete'
GROUP BY
    LOCATION_ID,
    SENSOR_DISPLAY_NAME
HAVING COUNT(DISTINCT SENSING_DATE) >= 300
ORDER BY
    AVG_PEDESTRIANS_PER_HOUR DESC
LIMIT 10;

-- Point 11: Advanced Query 1
-- Peak hour for each of the 10 busiest sensors in 2025

WITH TOP_SENSORS AS (
    SELECT
        LOCATION_ID,
        SENSOR_DISPLAY_NAME,
        AVG(PEDESTRIAN_COUNT) AS OVERALL_AVG_COUNT
    FROM S8149950_PEDESTRIAN_DB.ANALYTICS.PEDESTRIAN_COUNTS_CLEAN
    WHERE SENSING_YEAR = 2025
      AND DATA_QUALITY_STATUS = 'Complete'
    GROUP BY
        LOCATION_ID,
        SENSOR_DISPLAY_NAME
    HAVING COUNT(DISTINCT SENSING_DATE) >= 300
    ORDER BY OVERALL_AVG_COUNT DESC
    LIMIT 10
),

HOURLY_AVERAGES AS (
    SELECT
        P.LOCATION_ID,
        P.SENSOR_DISPLAY_NAME,
        P.HOUR_OF_DAY,
        P.HOUR_LABEL,
        COUNT(DISTINCT P.SENSING_DATE) AS OBSERVED_DAYS,
        ROUND(
            AVG(P.PEDESTRIAN_COUNT),
            2
        ) AS AVG_PEDESTRIANS_AT_HOUR
    FROM S8149950_PEDESTRIAN_DB.ANALYTICS.PEDESTRIAN_COUNTS_CLEAN P
    INNER JOIN TOP_SENSORS T
        ON P.LOCATION_ID = T.LOCATION_ID
       AND P.SENSOR_DISPLAY_NAME = T.SENSOR_DISPLAY_NAME
    WHERE P.SENSING_YEAR = 2025
      AND P.DATA_QUALITY_STATUS = 'Complete'
    GROUP BY
        P.LOCATION_ID,
        P.SENSOR_DISPLAY_NAME,
        P.HOUR_OF_DAY,
        P.HOUR_LABEL
),

RANKED_HOURS AS (
    SELECT
        *,
        DENSE_RANK() OVER (
            PARTITION BY
                LOCATION_ID,
                SENSOR_DISPLAY_NAME
            ORDER BY
                AVG_PEDESTRIANS_AT_HOUR DESC
        ) AS PEAK_HOUR_RANK
    FROM HOURLY_AVERAGES
)

SELECT
    LOCATION_ID,
    SENSOR_DISPLAY_NAME,
    HOUR_OF_DAY AS PEAK_HOUR,
    HOUR_LABEL AS PEAK_HOUR_LABEL,
    OBSERVED_DAYS,
    AVG_PEDESTRIANS_AT_HOUR
FROM RANKED_HOURS
WHERE PEAK_HOUR_RANK = 1
ORDER BY AVG_PEDESTRIANS_AT_HOUR DESC;

-- Point 12: Advanced Query 2
-- Compare each complete month with the same month one year earlier

WITH MONTHLY_METRICS AS (
    SELECT
        SENSING_YEAR,
        MONTH_NUMBER,
        MONTH_NAME,
        COUNT(DISTINCT SENSING_DATE) AS DAYS_OBSERVED,
        COUNT(DISTINCT LOCATION_ID) AS ACTIVE_SENSORS,
        SUM(PEDESTRIAN_COUNT) AS TOTAL_PEDESTRIANS,
        AVG(PEDESTRIAN_COUNT)
            AS AVG_PEDESTRIANS_PER_SENSOR_HOUR
    FROM S8149950_PEDESTRIAN_DB.ANALYTICS.PEDESTRIAN_COUNTS_CLEAN

    -- August is excluded because August 2024 and 2026 are partial
    WHERE MONTH_NUMBER <> 8

    GROUP BY
        SENSING_YEAR,
        MONTH_NUMBER,
        MONTH_NAME

    -- Include only complete calendar months
    HAVING COUNT(DISTINCT SENSING_DATE) =
        DAYOFMONTH(LAST_DAY(MIN(SENSING_DATE)))
),

YEARLY_COMPARISON AS (
    SELECT
        *,
        LAG(TOTAL_PEDESTRIANS) OVER (
            PARTITION BY MONTH_NUMBER
            ORDER BY SENSING_YEAR
        ) AS PREVIOUS_YEAR_TOTAL,

        LAG(AVG_PEDESTRIANS_PER_SENSOR_HOUR) OVER (
            PARTITION BY MONTH_NUMBER
            ORDER BY SENSING_YEAR
        ) AS PREVIOUS_YEAR_AVG,

        LAG(ACTIVE_SENSORS) OVER (
            PARTITION BY MONTH_NUMBER
            ORDER BY SENSING_YEAR
        ) AS PREVIOUS_YEAR_SENSORS
    FROM MONTHLY_METRICS
)

SELECT
    SENSING_YEAR AS CURRENT_YEAR,
    MONTH_NUMBER,
    MONTH_NAME,
    DAYS_OBSERVED,
    ACTIVE_SENSORS,
    PREVIOUS_YEAR_SENSORS,
    TOTAL_PEDESTRIANS,
    PREVIOUS_YEAR_TOTAL,

    ROUND(
        AVG_PEDESTRIANS_PER_SENSOR_HOUR,
        2
    ) AS CURRENT_AVG_PER_SENSOR_HOUR,

    ROUND(
        PREVIOUS_YEAR_AVG,
        2
    ) AS PREVIOUS_AVG_PER_SENSOR_HOUR,

    ROUND(
        100 * (
            AVG_PEDESTRIANS_PER_SENSOR_HOUR -
            PREVIOUS_YEAR_AVG
        ) / NULLIF(PREVIOUS_YEAR_AVG, 0),
        2
    ) AS YOY_CHANGE_PERCENT

FROM YEARLY_COMPARISON
WHERE PREVIOUS_YEAR_AVG IS NOT NULL
ORDER BY MONTH_NUMBER;